"""initial schema

Revision ID: 1420c68d935e
Revises: 
Create Date: 2026-06-14 15:58:30.532553
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1420c68d935e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charging_stations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('data_source', sa.String(length=8), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('network', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('num_dc_fast_ports', sa.Integer(), nullable=True),
    sa.Column('max_power_kw', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('connector_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("data_source IN ('NREL', 'OCM')", name='ck_station_data_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source', 'external_id', name='uq_station_source_extid')
    )
    op.create_index(op.f('ix_charging_stations_expires_at'), 'charging_stations', ['expires_at'], unique=False)
    op.create_table('loads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('origin_label', sa.String(length=160), nullable=False),
    sa.Column('origin_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('origin_lon', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('dest_label', sa.String(length=160), nullable=False),
    sa.Column('dest_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('dest_lon', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('weight_lb', sa.Integer(), nullable=False),
    sa.Column('pickup_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pickup_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_source IN ('synthetic', 'real')", name='ck_loads_data_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_loads_data_source'), 'loads', ['data_source'], unique=False)
    op.create_table('trucks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('variant', sa.String(length=120), nullable=False),
    sa.Column('usable_kwh', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('published_range_mi', sa.Integer(), nullable=False),
    sa.Column('gvwr_lb', sa.Integer(), nullable=False),
    sa.Column('max_charge_kw', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('base_consumption_kwh_per_mi', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('reference_payload_lb', sa.Integer(), nullable=False),
    sa.Column('spec_source_url', sa.String(length=500), nullable=False),
    sa.Column('spec_accessed_date', sa.Date(), nullable=False),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('truck_id', sa.Uuid(), nullable=True),
    sa.Column('load_id', sa.Uuid(), nullable=True),
    sa.Column('truck_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('load_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('soc_start_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reserve_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dwell_buffer_min', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('payload_coefficient_kwh_per_mi_per_ton', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('charge_efficiency', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('charge_soc_cap_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('energy_price_per_kwh_usd', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('routing_provider', sa.String(length=40), nullable=False),
    sa.Column('route_distance_mi', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('route_drive_hours', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('route_geometry', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('chargers_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('consumption_kwh_per_mi', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('energy_required_kwh', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('usable_energy_for_trip_kwh', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('charging_required', sa.Boolean(), nullable=False),
    sa.Column('energy_to_add_kwh', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('charge_time_hours', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('charge_cost_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_hours', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('projected_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('on_time', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verdict IN ('feasible', 'feasible_with_charging', 'infeasible')", name='ck_assessment_verdict'),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_verdict'), 'assessments', ['verdict'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessments_verdict'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_table('trucks')
    op.drop_index(op.f('ix_loads_data_source'), table_name='loads')
    op.drop_table('loads')
    op.drop_index(op.f('ix_charging_stations_expires_at'), table_name='charging_stations')
    op.drop_table('charging_stations')
    # ### end Alembic commands ###
