"""add num_charge_stops to assessments

Revision ID: 152d58666b67
Revises: ccbaa20ced31
Create Date: 2026-06-14 20:22:33.798191
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '152d58666b67'
down_revision: Union[str, None] = 'ccbaa20ced31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('num_charge_stops', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'num_charge_stops')
    # ### end Alembic commands ###
