"""time-aware assessment: time_mode, latest_departure, now_reference

Revision ID: 569b4c038151
Revises: 585f926ad7f8
Create Date: 2026-06-14 23:47:35.279213
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '569b4c038151'
down_revision: Union[str, None] = '585f926ad7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('time_mode', sa.String(length=16), server_default='arrive_by', nullable=False))
    op.add_column('assessments', sa.Column('latest_departure', sa.DateTime(timezone=True), nullable=False))
    op.add_column('assessments', sa.Column('now_reference', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'now_reference')
    op.drop_column('assessments', 'latest_departure')
    op.drop_column('assessments', 'time_mode')
    # ### end Alembic commands ###
