"""add stranded_at_mi to assessments

Revision ID: 585f926ad7f8
Revises: 152d58666b67
Create Date: 2026-06-14 22:00:32.249556
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '585f926ad7f8'
down_revision: Union[str, None] = '152d58666b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('stranded_at_mi', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'stranded_at_mi')
    # ### end Alembic commands ###
