"""add route_cache

Revision ID: ccbaa20ced31
Revises: 1420c68d935e
Create Date: 2026-06-14 16:14:07.503738
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ccbaa20ced31'
down_revision: Union[str, None] = '1420c68d935e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('origin_lat', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('origin_lon', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('dest_lat', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('dest_lon', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('distance_mi', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('duration_hours', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('geometry', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'origin_lat', 'origin_lon', 'dest_lat', 'dest_lon', name='uq_route_cache_key')
    )
    op.create_index(op.f('ix_route_cache_expires_at'), 'route_cache', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_cache_expires_at'), table_name='route_cache')
    op.drop_table('route_cache')
    # ### end Alembic commands ###
