"""loads: nullable absolute windows + relative offset columns

Revision ID: ee9e6fda87dc
Revises: 569b4c038151
Create Date: 2026-06-15 00:12:46.815705
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ee9e6fda87dc'
down_revision: Union[str, None] = '569b4c038151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loads', sa.Column('pickup_start_offset_h', sa.Numeric(precision=7, scale=2), nullable=True))
    op.add_column('loads', sa.Column('pickup_end_offset_h', sa.Numeric(precision=7, scale=2), nullable=True))
    op.add_column('loads', sa.Column('delivery_start_offset_h', sa.Numeric(precision=7, scale=2), nullable=True))
    op.add_column('loads', sa.Column('delivery_end_offset_h', sa.Numeric(precision=7, scale=2), nullable=True))
    op.alter_column('loads', 'pickup_window_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('loads', 'pickup_window_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('loads', 'delivery_window_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('loads', 'delivery_window_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loads', 'delivery_window_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('loads', 'delivery_window_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('loads', 'pickup_window_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('loads', 'pickup_window_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('loads', 'delivery_end_offset_h')
    op.drop_column('loads', 'delivery_start_offset_h')
    op.drop_column('loads', 'pickup_end_offset_h')
    op.drop_column('loads', 'pickup_start_offset_h')
    # ### end Alembic commands ###
